version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped
    environment:
      - APP_NAME=MyFlaskApp
    networks:
      - net1
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - net1
  redis:
    image: redis:4.0-alpine
    container_name: redis
    networks:
      - net1
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]

networks:
  net1:
