version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "80:80"
    networks:
      - net1
    command: gunicorn --bind :80 --worker-class gevent --log-level debug app:app
