# This is a Dockerfile

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y apache2 python3 python3-pip libapache2-mod-wsgi

COPY hello_flask.py REQUIREMENTS hello_flaskREST.wsgi /app/
RUN pip3 install -r /app/REQUIREMENTS

COPY hello_flaskREST.conf /etc/apache2/sites-available/
#RUN a2ensite hello_flaskREST

RUN a2dissite 000-default.conf
RUN a2ensite hello_flaskREST.conf

EXPOSE 80

WORKDIR /app

CMD /usr/sbin/apache2ctl -D FOREGROUND


# ENTRYPOINT ["python3"]

# CMD ["hello_flaskREST.py"]
