version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "80:80"
    networks:
      - net1
    command: gunicorn --bind :80 --worker-class gevent --log-level debug app:app

  redis1:
    image: redis:4.0-alpine
    container_name: redis1
    networks:
      - net1
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]

  redis2:
    image: redis:4.0-alpine
    container_name: redis2
    ports:
      - "6379:6379"
    networks:
      - net1
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]

networks:
  net1: